# Constants

DATABASE_URL = "sqlite:///healthbridge.db"

MIN_FIRST_NAME_LENGTH = 1
MAX_FIRST_NAME_LENGTH = 32

MIN_LAST_NAME_LENGTH = 1
MAX_LAST_NAME_LENGTH = 42

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 20

MIN_HEALTH_LENGTH = 2
MAX_HEALTH_LENGTH = 80

MIN_DESC_LENGTH = 2
MAX_DESC_LENGTH = 500

MIN_EMAIL_LENGTH = 6
MAX_EMAIL_LENGTH = 255

MIN_REMINDER_LENGTH = 2
MAX_REMINDER_LENGTH = 100

APPOINTMENT_ID = 1
MEDICATION_ID = 2

OVERDUE_ID = 1
UPCOMING_ID = 2
TAKEN_ID = 3
